OrdersHistoryWriterJob:
    Db:
        LogsConnString:
            settings-key: LogsConnString
            types:
                - AzureTableStorage
        OrdersConnString:
            settings-key: OrdersHistoryWriterJob-OrdersConnString
            types:
                - AzureTableStorage
        TradesConnString:
            settings-key: OrdersHistoryWriterJob-TradesConnString
            types:
                - AzureTableStorage
    Rabbit:
        ConnectionString:
            settings-key: GeneralRabbitMqConnectionString
            types:
                - RabbitMq
        ExchangeName: spot.matching.engine.out.events
    WarningPartitionsCount: 3000
    WarningPartitionQueueCount: 10000
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl